---
apiVersion: v1
kind: Pod                 
metadata:
  name: pd
  labels:
    app: pd
spec:
  containers:
  - name: pd
    image: pingcap/pd:latest
    ports:
      - containerPort: 2379
    args: ["--client-urls=http://127.0.0.1:2379"]
  #    - client-urls: http://pd-service:2379
  #    - peer-urls: http://0.0.0.0:2380
  #    - initial-cluster: pd1=http://0.0.0.0:2380
  #- name: tidb
  #  image: pingcap/tidb:latest
  #  ports:
  #    - containerPort: 10080
  #    - containerPort: 4000

---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: pd-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - protocol: TCP
    port: 2379
    targetPort: 2379
    #nodePort: 30002
  selector:
    app: pd         # Map any pod with label `app=go-hello-world` to this service
