---
apiVersion: v1
kind: Pod                 
metadata:
  name: tikv
  labels:
    app: tikv
spec:
  containers:
  - name: tikv
    image: pingcap/tikv:latest
    ports:
      - containerPort: 20160
    args: ["--pd=http://pd-service"]